name: push

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        alpine_ver: [latest]
        jdk_ver: [17, 8]
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: |
            ALPINE_VERSION=${{ matrix.alpine_ver }}
            JDK_VERSION=${{ matrix.jdk_ver }}
          push: true
          tags: s3vt/jdk:${{ matrix.jdk_ver }}
